### ISSUE TITLE
Unable to Launch

### ISSUE THREAD

**Issue by mizz141** [TPPIC/Test-Pack-Please-Ignore-2C#5]
I am Unable to Launch TPPI 2 Version 1.0.2 here is the Log.

FTB Launcher logs:
[10:28:02] [DEBUG] Main.main:171: Launcher arguments: []
[10:28:02] [DEBUG] Main.main:172: Launcher PID: 40440
[10:28:02] [DEBUG] Main.main:183: FTB Launcher CI Build #: 388, Git SHA: 9c2819d0a2e1
[10:28:02] [INFO] JGoogleAnalyticsTracker$2.run:484: AnalyticsBackgroundThread started
[10:28:02] [INFO] MainHelpers.printInfo:39: FTBLaunch starting up (version 1.4.12 Build: 10412)
[10:28:02] [DEBUG] MainHelpers.printInfo:40: System's default JVM: (This is not always used to launch MC)
[10:28:02] [DEBUG] MainHelpers.printInfo:41: Java version: 1.8.0_101
[10:28:02] [DEBUG] MainHelpers.printInfo:42: Java vendor: Oracle Corporation
[10:28:02] [DEBUG] MainHelpers.printInfo:43: Java home: C:\Program Files\Java\jre1.8.0_101
[10:28:02] [DEBUG] MainHelpers.printInfo:44: Java specification: Java Virtual Machine Specification version: 1.8 by Oracle Corporation
[10:28:02] [DEBUG] MainHelpers.printInfo:46: Java vm: Java HotSpot(TM) 64-Bit Server VM version: 25.101-b13 by Oracle Corporation
[10:28:02] [INFO] MainHelpers.printInfo:47: OS: Windows 10 10.0 (64-bit)
[10:28:02] [INFO] MainHelpers.printInfo:48: Launcher Install Dir: c:\ftb
[10:28:02] [INFO] MainHelpers.printInfo:49: System memory: 12926M free, 16267M total
[10:28:02] [DEBUG] OSUtils.printGPUinformation:752: GPU information:
AdapterRAM  Description                DriverDate                 DriverVersion  InstalledDisplayDrivers
2147483648  NVIDIA GeForce GTX 850M    20160223000000.000000-000  10.18.13.6200  nvd3dumx.dll,nvwgf2umx.dll,nvwgf2umx.dll,nvwgf2umx.dll,nvd3dum,nvwgf2um,nvwgf2um,nvwgf2um
1073741824  Intel(R) HD Graphics 4600  20160422000000.000000-000  20.19.15.4444  igdumdim64.dll,igd10iumd64.dll,igd10iumd64.dll,igd12umd64.dll,igdumdim32,igd10iumd32,igd10iumd32,igd12umd32
[10:28:02] [ERROR] OutputOverride.write:43: From Console: Nov 06, 2016 10:28:02 AM java.util.prefs.WindowsPreferences <init>
WARNUNG: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
[10:28:02] [INFO] JavaFinder.parseJavaVersion:175: The FTB Launcher has found the following Java versions installed:
[10:28:02] [INFO] JavaFinder.parseJavaVersion:177: Java Version: 1.8.0_101 sorted as: 1.8.0_101 32 Bit Java at : C:\Program Files (x86)\Java\jre1.8.0_101\bin\java.exe
[10:28:02] [INFO] JavaFinder.parseJavaVersion:177: Java Version: 1.8.0_101 sorted as: 1.8.0_101 64 Bit Java at : C:\Program Files\Java\jre1.8.0_101\bin\java.exe
[10:28:02] [INFO] JavaFinder.parseJavaVersion:177: Java Version: 1.8.0_101 sorted as: 1.8.0_101 64 Bit Java at : C:\Program Files\Java\jre1.8.0_101\bin\java.exe
[10:28:02] [INFO] JavaFinder.parseJavaVersion:204: Preferred: Java Version: 1.8.0_101 sorted as: 1.8.0_101 64 Bit Java at : C:\Program Files\Java\jre1.8.0_101\bin\java.exe
[10:28:02] [DEBUG] OSUtils.getProxy:77: ProxySelector: type: DIRECT, no proxy for http://ftb.cursecdn.com
[10:28:02] [DEBUG] OSUtils.getProxy:77: ProxySelector: type: DIRECT, no proxy for http://www.creeperrepo.net
[10:28:02] [DEBUG] DownloadUtils.run:450: DownloadUtils.run() starting
[10:28:02] [DEBUG] Benchmark.logBenchAs:73: Download Utils Balance (curse) took 64 ms.
[10:28:02] [DEBUG] Benchmark.logBenchAs:73: Download Utils Balance took 69 ms.
[10:28:02] [INFO] I18N.addFiles:97: [i18n] Fallback enUS loaded
[10:28:02] [INFO] I18N.setLocale:120: [i18n] deDE Deutsche Sprachdatei geladen!
[10:28:02] [INFO] LoadingDialog.advance:46: Checking installation location
[10:28:02] [DEBUG] Benchmark.logBenchAs:73: Download Utils Curse edges.json took 100 ms.
[10:28:02] [DEBUG] DownloadUtils.run:546: DL ready
[10:28:02] [INFO] DownloadUtils.run:579: Using download server Automatic:CurseCDN on host ftb.cursecdn.com (52.222.157.179)
[10:28:02] [DEBUG] Benchmark.logBenchAs:73: Download Utils Init took 100 ms.
[10:28:02] [INFO] LoadingDialog.advance:46: Loading user data
[10:28:03] [DEBUG] OSUtils.getMacAddress:412: Interface: Realtek PCIe GBE Family Controller : eth0
[10:28:03] [DEBUG] RetiredPacksLoader.run:66: Found 26packcodes
[10:28:03] [INFO] LoadingDialog.advance:46: Creating Console window
[10:28:03] [INFO] LoadingDialog.advance:46: Creating main window
[10:28:03] [DEBUG] AuthlibDLWorker.doInBackground:56: Loading Authlib...
[10:28:03] [DEBUG] Benchmark.logBenchAs:73: Modpack Loader http://ftb/MegaSharkPunch.xml took 532 ms.
[10:28:03] [INFO] ModpackLoader$XmlHtmlRunnable.handleXML:106: Loading modpack information for MegaSharkPunch.xml...
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 200 (Test Pack Please Ignore)
[10:28:03] [DEBUG] Benchmark.logBenchAs:73: Modpack Loader http://ftb/thirdparty.xml took 617 ms.
[10:28:03] [INFO] ModpackLoader$XmlHtmlRunnable.handleXML:106: Loading modpack information for thirdparty.xml...
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 100 (Space Astronomy)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 101 (InfiTech 2)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 102 (TerraFirmaPunk)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 103 (The Ferret Business)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 104 (Simply Magic)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 105 (BeeHappy)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 106 (Regrowth)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 107 (Crash Landing)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 108 (Agrarian Skies: Hardcore Quest)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 109 (Vanilla Minecraft)
[10:28:03] [DEBUG] Benchmark.logBenchAs:73: Modpack Loader http://ftb/modpacks.xml took 664 ms.
[10:28:03] [INFO] ModpackLoader$XmlHtmlRunnable.handleXML:106: Loading modpack information for modpacks.xml...
[10:28:03] [INFO] OptionsPane.<init>:172: [i18n] Added 0 enUS to options pane
[10:28:03] [INFO] OptionsPane.<init>:172: [i18n] Added 1 cyGB to options pane
[10:28:03] [INFO] OptionsPane.<init>:172: [i18n] Added 2 daDK to options pane
[10:28:03] [INFO] OptionsPane.<init>:172: [i18n] Added 3 deDE to options pane
[10:28:03] [INFO] OptionsPane.<init>:172: [i18n] Added 4 enGB to options pane
[10:28:03] [INFO] OptionsPane.<init>:172: [i18n] Added 5 enUS to options pane
[10:28:03] [INFO] OptionsPane.<init>:172: [i18n] Added 6 esES to options pane
[10:28:03] [INFO] OptionsPane.<init>:172: [i18n] Added 7 fiFI to options pane
[10:28:03] [INFO] OptionsPane.<init>:172: [i18n] Added 8 frCA to options pane
[10:28:03] [INFO] OptionsPane.<init>:172: [i18n] Added 9 frFR to options pane
[10:28:03] [INFO] OptionsPane.<init>:172: [i18n] Added 10 itIT to options pane
[10:28:03] [INFO] OptionsPane.<init>:172: [i18n] Added 11 maHU to options pane
[10:28:03] [INFO] OptionsPane.<init>:172: [i18n] Added 12 nlNL to options pane
[10:28:03] [INFO] OptionsPane.<init>:172: [i18n] Added 13 noNO to options pane
[10:28:03] [INFO] OptionsPane.<init>:172: [i18n] Added 14 plPL to options pane
[10:28:03] [INFO] OptionsPane.<init>:172: [i18n] Added 15 ptBR to options pane
[10:28:03] [INFO] OptionsPane.<init>:172: [i18n] Added 16 ptPT to options pane
[10:28:03] [INFO] OptionsPane.<init>:172: [i18n] Added 17 ruRU to options pane
[10:28:03] [INFO] OptionsPane.<init>:172: [i18n] Added 18 svSE to options pane
[10:28:03] [INFO] OptionsPane.<init>:172: [i18n] Added 19 zhCN to options pane
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 0 (FTB Infinity Lite 1.10)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 1 (FTB Presents HermitPack)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 2 (FTB Infinity Evolved 1.7)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 3 (FTB Unstable 1.10)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 4 (FTB Inventions)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 5 (FTB Presents Crackpack)
[10:28:03] [INFO] I18N.setLocale:120: [i18n] deDE Deutsche Sprachdatei geladen!
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 6 (FTB Presents Skyfactory 2.5)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 7 (FTB Infinity Evolved Skyblock)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 8 (FTB Horizons: Daybreaker)
[10:28:03] [WARN] RSSReader.readRSS:49: News download failed
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 9 (FTB Vanilla+)
[10:28:03] [DEBUG] Benchmark.logBench:59: NewsUtils took 100 ms.
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 10 (FTB Departed)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 11 (FTB Trident)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 12 (FTB Presents Cloud 9)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 13 (FTB Presents Direwolf20)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 14 (FTB Lite 3)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 15 (FTB Mage Quest)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 16 (FTB Resurrection)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 17 (Pax Prime 2015 Map)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 18 (Monster)
[10:28:03] [DEBUG] Benchmark.logBenchAs:73: UnreadNews Init took 0 ms.
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 19 (Direwolf20)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 20 (Horizons)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 21 (Tech World 2)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 22 (Magic World 2)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 23 (FTBLite2)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 24 (FTB Unleashed)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 25 (FTB Ultimate)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 26 (Unstable 1.7.x (Public Beta Test Pack))
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 27 (FTB Lite)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 28 (Direwolf20 1.5 v2)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 29 (Direwolf20 Pack)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 30 (MindCrack Pack)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 31 (YogCraft Modpack)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 32 (FTB Unhinged)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 33 (Magic World)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 34 (Tech World)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 35 (Pax South 2015 Map)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 36 (Pax Prime 2014 Map)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 37 (Pax East 2014 Map)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 38 (Pax Challenge Pack 2013)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 39 (Feed The Beast Retro SSP)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 40 (Feed The Beast Retro SMP)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 41 (Slow's Stream Pack)
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 42 (Feed The Beast Beta Pack A)
[10:28:03] [INFO] AuthlibDLWorker.downloadJars:147: Local Authlib Version is good, skipping Download
[10:28:03] [INFO] AuthlibDLWorker.doInBackground:68: Adding Authlib to Classpath
[10:28:03] [DEBUG] Benchmark.logBenchAs:73: Modpack Loader http://ftb/SuperWhaleKick.xml took 783 ms.
[10:28:03] [INFO] ModpackLoader$XmlHtmlRunnable.handleXML:106: Loading modpack information for SuperWhaleKick.xml...
[10:28:03] [DEBUG] ModpackLoader$XmlHtmlRunnable.handleXML:148: Adding pack 300 (TPPI2)
[10:28:03] [DEBUG] Benchmark.logBenchAs:73: All modpack lists loaded took 786 ms.
[10:28:03] [DEBUG] Benchmark.logBench:59: Waiting for main window took 0 ms.
[10:28:03] [INFO] MapLoader.run:43: loading map information...
[10:28:03] [INFO] TexturePackLoader.run:43: loading texture pack information...
[10:28:03] [INFO] LoadingDialog.advance:46: Setting up Launcher
[10:28:03] [DEBUG] UpdateChecker.<init>:71: Launcher Install path: C:\Users\René\Desktop\FTB_Launcher.exe
[10:28:03] [INFO] LoadingDialog.advance:46: Downloading pack data
[10:28:03] [DEBUG] Benchmark.logBenchAs:73: MapLoader run  took 47 ms.
[10:28:03] [DEBUG] Benchmark.logBenchAs:73: Launcher Startup(maps or texturepacks loaded) took 1434 ms.
[10:28:03] [INFO] LoadingDialog.advance:46: Opening main window
[10:28:03] [DEBUG] Benchmark.logBenchAs:73: Launcher Startup(Modpacks loaded) took 1449 ms.
[10:28:03] [DEBUG] LaunchFrame$14.run:451: Last used packs: FTBInfinity TPPI2
[10:28:03] [DEBUG] Benchmark.logBenchAs:73: Texture Pack Load  took 62 ms.
[10:28:03] [DEBUG] Benchmark.logBenchAs:73: Launcher Startup(maps and texturepacks loaded) took 1449 ms.
[10:28:03] [DEBUG] Benchmark.logBenchAs:73: Authlib DL Worker Init took 539 ms.
[10:28:03] [DEBUG] UpdateChecker.shouldUpdate:132: updater: buildjenk 388 < betajenk 341|| version 10412 < 10408
[10:28:03] [DEBUG] UpdateChecker.shouldUpdate:133: latest = 10412
[10:28:04] [DEBUG] Benchmark.logBenchAs:73: Launcher Startup(main window opened and ready to use) took 1687 ms.
[10:28:04] [INFO] MapUtils$6.run:250: Adding map 1 (Direwolf20 Map Ep.40)
[10:28:04] [INFO] MapUtils$6.run:250: Adding map 2 (Direwolf20 Map Ep.50)
[10:28:04] [INFO] MapUtils$6.run:250: Adding map 3 (Direwolf20 Map Ep.80)
[10:28:04] [INFO] MapUtils$6.run:250: Adding map 4 (FTB Normal)
[10:28:04] [INFO] MapUtils$6.run:250: Adding map 5 (FTB Insanity)
[10:28:04] [INFO] TexturepackPane$6.run:237: Adding texture pack 1 (Soartex Fanver)
[10:28:04] [INFO] TexturepackPane$6.run:237: Adding texture pack 2 (Jadedcat Mixpack)
[10:28:04] [INFO] TexturepackPane$6.run:237: Adding texture pack 3 (Invictus)
[10:28:04] [INFO] TexturepackPane$6.run:237: Adding texture pack 4 (Faithful)
[10:28:04] [INFO] TexturepackPane$6.run:237: Adding texture pack 5 (JohnSmith Technicians Remix)
[10:28:04] [INFO] TexturepackPane$6.run:237: Adding texture pack 6 (Familiar yet Different)
[10:28:11] [DEBUG] LaunchFrame.doLaunch:946: Selected user: saved password: true
[10:28:11] [DEBUG] LaunchFrame.doLaunch:947: Selected user: will save auth token if online: true
[10:28:11] [INFO] LaunchFrame.doLogin:536: Logging in...
[10:28:11] [DEBUG] OSUtils.getProxy:77: ProxySelector: type: DIRECT, no proxy for https://authserver.mojang.com/authenticate
[10:28:11] [DEBUG] AuthlibHelper.authenticateWithAuthlib:67: Email address given
[10:28:11] [INFO] AuthlibHelper.authenticateWithAuthlib:68: Beginning authlib authentication attempt
[10:28:11] [INFO] AuthlibHelper.authenticateWithAuthlib:69: successfully created YggdrasilAuthenticationService
[10:28:11] [DEBUG] AuthlibHelper.authenticateWithAuthlib:76: mojangData was passed to current method
[10:28:11] [DEBUG] AuthlibHelper.authenticateWithAuthlib:79: Loading mojangData into authlib
[10:28:12] [DEBUG] AuthlibHelper.authenticateWithAuthlib:152: Authentication is valid 
[10:28:12] [DEBUG] AuthlibHelper.authenticateWithAuthlib:155: loggedIn() && CanPlayOnline()
[10:28:12] [DEBUG] AuthlibHelper.authenticateWithAuthlib:159: Authentication done, returning LoginResponse
[10:28:12] [DEBUG] Benchmark.logBenchAs:73: Login Worker Run took 316 ms.
[10:28:12] [DEBUG] LaunchFrame$16.done:580: responseStr: good
[10:28:12] [INFO] LaunchFrame$16.done:583: Login complete.
[10:28:12] [DEBUG] User.writeObject:185: starting...
[10:28:12] [DEBUG] LaunchFrame$16.done:587: user data saved
[10:28:12] [DEBUG] LaunchFrame.runGameUpdater:634: ForceUpdate: false
[10:28:12] [DEBUG] LaunchFrame.runGameUpdater:635: installPath: c:\ftb
[10:28:12] [DEBUG] LaunchFrame.runGameUpdater:636: pack dir: TPPI2
[10:28:12] [DEBUG] LaunchFrame.runGameUpdater:637: pack check path: TPPI2\version
[10:28:12] [DEBUG] LaunchFrame.checkVersion:612: verFile: 1.0.2 onlineVersion/getPackVer(): 1.0.2 onlineVersion/getVersion(): 1.0.2
[10:28:12] [INFO] MCInstaller.gatherAssets:127: Checking local assets file, for MC version 1.7.10 Please wait! 
[10:28:12] [DEBUG] MCInstaller.gatherAssets:132: Checking pack libraries
[10:28:12] [DEBUG] MCInstaller.gatherAssets:184: Checking minecraft version json
[10:28:12] [DEBUG] MCInstaller.gatherAssets:199: checking minecraft libraries
[10:28:12] [DEBUG] MCInstaller.gatherAssets:267: Checking minecraft assets
[10:28:13] [DEBUG] MCInstaller.gatherAssets:281: Starting TaskHandler to check MC assets
[10:28:13] [DEBUG] Benchmark.logBenchAs:73: parallel asset check took 143 ms.
[10:28:13] [INFO] MCInstaller.launchMinecraft:328: Setting up native libraries for TPPI2 v 1.0.2 MC 1.7.10
[10:28:13] [DEBUG] MCInstaller.launchMinecraft:354: packbaseJSON 1.7.10
[10:28:14] [INFO] MCLauncher.syncAssets:288: Syncing Assets:
[10:28:14] [INFO] MCLauncher.launchMinecraft:86: Java Path: C:\Program Files\Java\jre1.8.0_101\bin\javaw.exe
[10:28:14] [INFO] MCLauncher.launchMinecraft:87: Pack: TPPI2 1.7.10
[10:28:14] [INFO] MCLauncher.setMemory:271: Setting MinMemory to 256
[10:28:14] [INFO] MCLauncher.setMemory:273: Setting MaxMemory to 10496
[10:28:14] [DEBUG] MCInstaller.launchMinecraft:428: MC PID: 40164
[10:28:14] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[10:28:14] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: cpw.mods.fml.common.launcher.FMLTweaker
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_101]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_101]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_101]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[10:28:15] [DEBUG] Benchmark.logBenchAs:73: UnreadNews Init took 0 ms.
[10:28:27] Logs copied to clipboard

**Comment by XxXYaJrAbXxX** [comment]
Just to clarify, this is the error: http://pastebin.com/9ztgxhsn

**Comment by m4sterP** [comment]
It's certainly not a general problem. Have you tried updating Java and/or installing the mod pack again? Also: do you use the Curse or FTB Launcher? Have you tried using them both?

**Comment by mizz141** [comment]
I Just updated my Java (Since then i didnt try to Launch) and im jusing the FTB Launcher because the Curse one is shit...

**Comment by XxXYaJrAbXxX** [comment]
Try launching from the curse launcher as the FTB launcher is outdated and is not longer updated. The FTB launcher is less stable and has other issues such as memory leaks. I will try and recreate your issue when I get home in an hour if your problem still persists

**Comment by XxXYaJrAbXxX** [comment]
I am unable to replicate this issue, on the FTB launcher go to the options tab and click the "Force update?" button, and then go to 3rd party modpacks and select TPPI2 and launch. This will cause TPPI2 to redownload and reinstall itself. This should hopefully fix your issue. If not, please post the error on www.pastebin.com or a similar site.
